name: Issue

on:
  issues:
     types: [opened]

jobs:
   issue:
     runs-on: ubuntu-lates
     steps: 
       - name: Comment
         uses: actions/github-script@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }} 
           script: |
              github.issues.createComment({
                issues_number: context.issues.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thanks for opening this issue!'
              })