#  Criar um pipeline no github Actions que será executado quando um psuh for realizado
# Para a branch main e escreva na tela "Olá, mundo"

name: Push

on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello Word
        run: echo "Olá, Mundo!"