# Crie um pipeline no Githu actions que será executado quando um PR for aberto
# Inclua o seguinte comentario no PR: "Obrigado pela sua alteração."

name: PR

on:
  pull_request:
     types: [opened]

jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
        pull-requests: write
        issues: write
     steps: 
       - name: Comment
         uses: actions/github-script@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }} 
           script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Obrigado pela alteração.'
              })